version: '3'
services:
  jenkins:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    image: myjenkins
    container_name: myjenkins
    ports:
      - "8080:8080"
    volumes:
      - ../my_marvin.yml:/var/jenkins_home/casc_configs/my_marvin.yml
      - ../job_dsl.groovy:/var/jenkins_home/casc_configs/job_dsl.groovy
    restart: on-failure